# Generated by Django 2.1.4 on 2020-07-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('codigo_accion', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccionesRealizadasUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Accion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True)),
                ('domicilio', models.CharField(max_length=150, null=True)),
                ('ciudad', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('fecha_alta_entrega', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura_compra', models.DateField()),
                ('fecha_alta_factura', models.DateField()),
                ('importe_neto_gravado', models.FloatField()),
                ('importe_total', models.FloatField()),
                ('iva27', models.FloatField()),
                ('iva21', models.FloatField()),
                ('iva105', models.FloatField()),
                ('iva0', models.FloatField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEntregaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta_item_entrega', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('esEntrega', models.BooleanField()),
                ('entregaCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsEntrega', to='api.EntregaCliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.FloatField()),
                ('unidad_medida', models.CharField(max_length=10)),
                ('alicuotaIVA', models.FloatField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
                ('facturaCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsFactura', to='api.FacturaCompra')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsOrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden_compra', models.DateField()),
                ('fecha_alta_orden', models.DateField()),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioHistoricoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('importe', models.FloatField()),
                ('itemFactura', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ItemsFactura')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('factor_multiplicacion', models.FloatField(default=1)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
                ('familiaProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FamiliaProducto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=60)),
                ('domicilio', models.CharField(max_length=70)),
                ('ingresos_brutos', models.CharField(max_length=10)),
                ('fecha_inicio_actividades', models.DateField()),
                ('condicionIVA', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('MO', 'Monotributista'), ('EX', 'Exento'), ('NR', 'No Responsable'), ('CF', 'Consumidor Final')], max_length=2)),
                ('cuit', models.CharField(max_length=11)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoLimpiezaCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=60, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistoricoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('estacion_kanban', models.CharField(choices=[('OC_IN', 'Ingreso de Orden de Compra'), ('OC_OUT', 'Egreso de Orden de Compra'), ('ST_IN', 'Ingreso de Stock'), ('ST_OUT', 'Egreso de Stock')], max_length=6, null=True)),
                ('estado', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('itemEntrega', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ItemEntregaCliente')),
                ('itemFactura', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ItemsFactura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_usuario', models.CharField(choices=[('EMP', 'Empleado'), ('REP', 'Repartidor'), ('SUP', 'Supervisor'), ('ADM', 'Administrador')], max_length=3)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('accionesPermitidas', models.ManyToManyField(to='api.Accion')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TipoProducto'),
        ),
        migrations.AddField(
            model_name='preciohistoricoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preciosProducto', to='api.Producto'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='usuario_alta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsordencompra',
            name='ordenCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsOrdenCompra', to='api.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='itemsordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producto'),
        ),
        migrations.AddField(
            model_name='itemsfactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Producto'),
        ),
        migrations.AddField(
            model_name='itementregacliente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productosEntrega', to='api.Producto'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='usuario_alta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregacliente',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado'),
        ),
        migrations.AddField(
            model_name='entregacliente',
            name='punto_limpieza_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.PuntoLimpiezaCliente'),
        ),
        migrations.AddField(
            model_name='entregacliente',
            name='usuario_alta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estado'),
        ),
    ]
