# Generated by Django 2.1.4 on 2020-05-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200507_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciohistoricoproducto',
            name='isCurrent',
        ),
        migrations.AlterField(
            model_name='entregacliente',
            name='punto_limpieza_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.PuntoLimpiezaCliente'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Proveedor'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='usuario_alta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Usuario'),
        ),
        migrations.AlterField(
            model_name='itementregacliente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productosEntrega', to='api.Producto'),
        ),
        migrations.AlterField(
            model_name='itemsfactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='familiaProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FamiliaProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipoProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TipoProducto'),
        ),
    ]
