# Generated by Django 2.1.4 on 2020-05-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200528_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='codigo',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
