# Generated by Django 2.1.4 on 2020-05-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200530_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='entregacliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='facturacompra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='estado',
        ),
    ]
