# Generated by Django 2.1.4 on 2020-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200530_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
